### ISSUE TITLE
Leetcode 9 Palindrome Number

### ISSUE THREAD

**Issue by s0l0ist** [warycat/rustgym#8]
The previous solution which contains a `while` loop is actually quite slow. The example solution could be optimized to be a modified version of the [integer reverse digits solution](https://github.com/warycat/rustgym/issues/7) that executes in O(1). 

```
impl Solution {
    pub fn is_palindrome(x: i32) -> bool {
        if x < 0 {
            return false
        }
        
        let x_str = x.abs()
            .to_string()
            .chars()
            .rev()
            .collect::<String>();
        
        match x_str.parse::<i32>() {
            Ok(n) => n == x,
            Err(_e) => false
        }
    }
}
```

**Comment by warycat** [comment]
It's O(1) because the integer is always within 32bits.

**Comment by s0l0ist** [comment]
To be fair, I'm not sure of the time complexity for string parsing integers of a given width (i32 in this case). I'm assuming this is constant time.

I think the previous solution's while loop is O(log n) where `n` is proportional to the value `x`.

**Comment by safrannn** [comment]
@s0l0ist There's not a big difference using numbers or string, though in practice using number would be somewhat faster than converting it to string and back. I've added the string method in the solution as comments.

**Comment by s0l0ist** [comment]
@safrannn Yeah you're right. Just did the bench:

```
running 2 tests
test is_palindrome_int    ... bench:       4,177 ns/iter (+/- 1,219)
test is_palindrome_string ... bench:     191,426 ns/iter (+/- 29,389)
```
